<?php

return [
    'map' => [
        'superadmin.dashboard' => 'dashboard',
        'admin.dashboard' => 'dashboard',
        'manager.dashboard' => 'dashboard',
        'superadmin.department.index' => 'department',
        'admin.department.index' => 'department',
        'superadmin.manage.dock.index' => 'dock.management',
        'admin.manage.dock.index' => 'dock.management',
        'manager.manage.dock.index' => 'dock.management',
        'superadmin.manage.dock.panel' => 'dock.panel',
        'admin.manage.dock.panel' => 'dock.panel',
        'manager.manage.dock.panel' => 'dock.panel',
        'superadmin.devices.pending' => 'devices.pending',
        'admin.devices.pending' => 'devices.pending',
        'superadmin.device.index' => 'device',
        'admin.device.index' => 'device',
        'manager.device.index' => 'device',
        'superadmin.company.map' => 'company-map',
        'admin.company.map' => 'company-map',
        'manager.company.map' => 'company-map',
        'superadmin.user.index' => 'user',
        'admin.user.index' => 'user',
        'manager.user.index' => 'user',
        'superadmin.profiles.index' => 'profiles',
        'superadmin.permissions.index' => 'permissions',
        'admin.permissions.index' => 'permissions',
        'superadmin.configuration.index' => 'configuration',
        'superadmin.configuration.bot.index' => 'configuration',
        'admin.configuration.index' => 'configuration',
        'manager.configuration.index' => 'configuration',
        'superadmin.logs.index' => 'logs',
        'admin.logs.index' => 'logs',
        'manager.logs.index' => 'logs',
        'superadmin.notification.index' => 'notification',
        'admin.notification.index' => 'notification',
        'manager.notification.index' => 'notification',
    ],
];
